### ISSUE TITLE
Unofficial HN API broken?

### ISSUE THREAD

**Issue by MaBeuLux88** [codepope/hnnode#2]
Hey @codepope :-) !

I hope you are well!
Looks like the stream API isn't delivering anymore... Any plan or idea to fix this?

https://github.com/codepope/hnnode/blob/69b594c076ebbc77b8cc000ad5a0f612f9287005/server.js#L41

Cheers, 
Maxime.

**Comment by codepope** [comment]
Well, as the issue is clearly upstream, it isn't something I have time to currently address.

**Comment by MaBeuLux88** [comment]
Looks like it's back online now. Maybe the admin got my email and did something. Good news!
